# Generated by Django 4.1.2 on 2022-10-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
